Repository codesquad-members-2024/fe-data-fetching, pull requests merged in 2024-04, with the labels that each got.

#3 [Schnee] 초기 페이지 구현 및 flux 구조 일부 추가
  .gitignore
  App.ts
  README.md
  data/news.json
  package.json
  routes/index.ts
  routes/news.ts
  routes/search.ts
  src/css/main.css
  src/index.html
  src/ts/Main.ts
  src/ts/action/Actions.ts
  src/ts/api/NewsApi.ts
  src/ts/constants.ts
  src/ts/dispatcher/Dispatcher.ts
  src/ts/event/EventHandler.ts
  src/ts/store/Store.ts
  src/ts/view/View.ts
  tsconfig.json
Labels: midpoint

#4 [George]: express 초기 세팅 및 tsconfig esm타입 설정, json 파싱
  .gitignore
  README.md
  app.js
  bin/www
  package-lock.json
  package.json
  public/src/controller/eventController.ts
  public/src/data/headlines.json
  public/src/data/newsContents.json
  public/src/main.ts
  public/src/model/newsAPI.ts
  public/src/model/newsModel.ts
  public/src/view/viewRenderer.ts
  public/stylesheets/index.css
  public/stylesheets/reset.css
  routes/index.js
  routes/newsContents.js
  routes/newsTitle.js
  tsconfig.json
  views/index.ejs
Labels: midpoint

#8 [Woody] 초기 페이지 뉴스 콘텐츠 보여주기
  .gitignore
  README.md
  app.js
  bin/www
  package.json
  public/css/reset.css
  public/css/style.css
  public/data/newsDatas.json
  public/js/contents.js
  public/js/eventHandler.js
  public/js/index.js
  public/js/newsDataFetch.js
  public/js/newsDataUpdate.js
  routes/index.js
  routes/news.js
  routes/users.js
  views/error.jade
  views/index.jade
  views/layout.jade
Labels: final

#9 [Schnee] 미션 최종 구현
  App.ts
  README.md
  routes/index.ts
  routes/news.ts
  routes/search.ts
  routes/utils.ts
  src/css/main.css
  src/img/loading.gif
  src/ts/Main.ts
  src/ts/action/Actions.ts
  src/ts/api/NewsApi.ts
  src/ts/constants.ts
  src/ts/event/EventHandler.ts
  src/ts/store/Store.ts
  src/ts/view/Renderer.ts
  src/ts/view/Updating.ts
Labels: final

#10 [Mime] 데이터 통신
  .gitignore
  app/app.js
  app/db/news.json
  app/public/css/style.css
  app/public/css/view/loading.css
  app/public/css/view/news-header.css
  app/public/css/view/news-main.css
  app/public/js/apis/news.js
  app/public/js/apis/newsList.js
  app/public/js/main.js
  app/public/js/views/newsTitle.js
  app/public/ts/apis/news.ts
  app/public/ts/apis/newsList.ts
  app/public/ts/main.ts
  app/public/ts/utils/delay.ts
  app/public/ts/utils/types.d.ts
  app/public/ts/views/header.ts
  app/public/ts/views/newsDescription.ts
  app/public/ts/views/newsTitle.ts
  app/routes/news.js
  app/tsconfig.json
  app/views/index.ejs
  app/views/newsComponents/main.ejs
Labels: final

#1 [marron] 기본 화면 구현
  .gitignore
  README.md
  app.js
  bin/www
  data/news.json
  package.json
  public/css/reset.css
  public/css/style.css
  public/img/loding.gif
  public/js/components/delay.js
  public/js/main.js
  public/js/view/news.js
  public/js/view/onEvent.js
  public/js/view/timer.js
  routes/index.js
  routes/news.js
  tsconfig.json
  views/error.jade
  views/index.jade
Labels: midpoint, final

#2 [Saturn] 업데이트와 에러 처리
  .gitignore
  app.js
  data/headlines.json
  package-lock.json
  package.json
  public/constants/constants.js
  public/css/app.css
  public/image/Rocket-unscreen.gif
  public/js/index.js
  public/js/initialPage.js
  public/js/loading.js
  public/js/newsListBtn.js
  public/js/render.js
  public/js/update.js
  public/js/utils.js
  routes/api.js
  routes/index.js
  utils/catchAsync.js
  utils/jsonParser.js
  views/error.ejs
  views/home.ejs
Labels: midpoint, final
